### ISSUE TITLE
イベント作成者のみスタート押せるようにする

### ISSUE THREAD

**Issue by Mokosu-bit** [Mokosu-bit/warigam#60]
## 概要
イベント作成者のみスタート押せるようにする。
その他調整。
## ToDo
- [x] ビューでイベント作成者以外は「スタート」を非表示にする
- [x] 参加を押した時、確認アラートを表示し、参加キャンセルはなくす
- [x] 作成者のみ編集できるようにする
- [x] イベント非表示時間を、作成から1時間に変更
